#ifndef GREEKLETTERS
    #define GREEKLETTERS

    #define GREEK_Alpha "Α"
    #define GREEK_Beta "Β"
    #define GREEK_Gamma "Γ"
    #define GREEK_Delta "Δ"
    #define GREEK_Epsilon "Ε"
    #define GREEK_Zeta "Ζ"
    #define GREEK_Eta "Η"
    #define GREEK_Theta "Θ"
    #define GREEK_Iota "Ι"
    #define GREEK_Kappa "Κ"
    #define GREEK_Lambda "Λ"
    #define GREEK_Mu "Μ"
    #define GREEK_Nu "Ν"
    #define GREEK_Xi "Ξ"
    #define GREEK_Omicron "Ο"
    #define GREEK_Pi "Π"
    #define GREEK_Rho "Ρ"
    #define GREEK_Sigma "Σ"
    #define GREEK_Tau "Τ"
    #define GREEK_Upsilon "Υ"
    #define GREEK_Phi "Φ"
    #define GREEK_Chi "Χ"
    #define GREEK_Psi "Ψ"
    #define GREEK_Omega "Ω"

    #define GREEK_alpha "α"
    #define GREEK_beta "β"
    #define GREEK_gamma "γ"
    #define GREEK_delta "δ"
    #define GREEK_epsilon "ε"
    #define GREEK_zeta "ζ"
    #define GREEK_eta "η"
    #define GREEK_theta "θ"
    #define GREEK_iota "ι"
    #define GREEK_kappa "κ"
    #define GREEK_lambda "λ"
    #define GREEK_mu "μ"
    #define GREEK_nu "ν"
    #define GREEK_xi "ξ"
    #define GREEK_omicron "ο"
    #define GREEK_pi "π"
    #define GREEK_rho "ρ"
    #define GREEK_sigma "σ"
    #define GREEK_tau "τ"
    #define GREEK_upsilon "υ"
    #define GREEK_phi "φ"
    #define GREEK_chi "χ"
    #define GREEK_psi "ψ"
    #define GREEK_omega "ω"

#endif //ifndef GREEKLETTERS